ALTER TABLE artworks ADD COLUMN original_path TEXT NOT NULL DEFAULT '';
ALTER TABLE artworks ADD COLUMN thumbnail_path TEXT NOT NULL DEFAULT '';
ALTER TABLE artworks ADD COLUMN medium_path TEXT NOT NULL DEFAULT '';
ALTER TABLE artworks ADD COLUMN museum_path TEXT NOT NULL DEFAULT '';
ALTER TABLE artworks ADD COLUMN large_path TEXT NOT NULL DEFAULT '';
